courses/urls.py
from django.conf.urls import include,url
from . import views

urlpatterns = [
    url(r'^$', views.course_list, name='course_list'),
    url(r'(?P<course_pk>\d+)/t(?P<step_pk>\d+)/$', views.text_detail, name='text_detail'),
    url(r'(?P<course_pk>\d+)/q(?P<step_pk>\d+)/$', views.quiz_detail, name='quiz_detail'),
    url(r'(?P<course_pk>\d+)/create_quiz/$', views.quiz_create, name='create_quiz'),
    url(r'(?P<course_pk>\d+)/edit_quiz(?P<quiz_pk>\d+)/$', views.quiz_edit, name='edit_quiz'),
    url(r'(?P<quiz_pk>\d+)/create_question/(?P<question_type>mc|tf)/$', views.create_question, name='create_question'),
    url(r'(?P<quiz_pk>\d+)/edit_question(?P<question_pk>\d+)/$', views.edit_question, name='edit_question'),
    url(r'(?P<question_pk>\d+)/create_answer/$', views.answer_form, name='create_answer'),
    url(r'(?P<pk>\d+)/$', views.course_detail, name='course_detail'),  # This url should be under the step_detail url.
]

learning_site/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include,url
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^courses/', include('courses.urls')),
    url(r'^', include('accounts.urls')),
    url(r'^suggest/$', views.suggestion_view, name='suggestion'),
    url(r'^$', views.home, name='home'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.urls import reverse
from django.db import models

class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title



class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    class Meta:
        abstract = True
        ordering = ['order',]

    def __str__(self):
        return self.title


class Text(Step):
    content = models.TextField(blank=True, default='')

    def get_absolute_url(self):
        return reverse('text_detail', kwargs={'course_pk': self.course_id, 'step_pk': self.id})


class Quiz(Step):
    total_questions = models.IntegerField(default=4)

    class Meta:
        verbose_name_plural = "Quizzes"

    def get_absolute_url(self):
        return reverse('quiz_detail', kwargs={'course_pk': self.course_id, 'step_pk': self.id})


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    order = models.IntegerField(default=0)
    prompt = models.TextField()

    class Meta:
        ordering = ['order',]

    def get_absolute_url(self):
        return self.quiz.get_absolute_url()

    def __str__(self):
        return self.prompt


class MultipleChoiceQuestion(Question):
    shuffle_answers = models.BooleanField(default=False)

class TrueFalseQuestion(Question):
    pass


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    order = models.IntegerField(default=0)
    text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)

    class Meta:
        ordering = ['order',]

    def __str__(self):
        return self.text

courses/forms.py
from django import forms

from . import models

class QuizForm(forms.ModelForm):
    class Meta:
        model = models.Quiz
        fields = [
            'title',
            'description',
            'order',
            'total_questions',
        ]


class QuestionForm(forms.ModelForm):
    class Media:
        css = {'all':('courses/css/order.css',)}
        js = (
            'courses/js/vendor/jquery.fn.sortable.min.js',
            'courses/js/order.js'
        )


class TrueFalseQuestionForm(QuestionForm):
    class Meta:
        model = models.TrueFalseQuestion
        fields = [
            'order',
            'prompt',
        ]


class MultipleChoiceQuestionForm(QuestionForm):
    class Meta:
        model = models.MultipleChoiceQuestion
        fields = [
            'order',
            'prompt',
            'shuffle_answers',
        ]



class AnswerForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = [
            'order',
            'text',
            'correct',
        ]

AnswerFormSet = forms.modelformset_factory(
    models.Answer,
    form = AnswerForm,
    extra = 2,
)


AnswerInlineFormSet = forms.inlineformset_factory(
    models.Question,
    models.Answer,
    extra = 2,
    fields = ('order', 'text', 'correct'),
    formset = AnswerFormSet,
    min_num = 1,
)

courses/views.py
from itertools import chain
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from . import forms
from . import models


def course_list(request):
    courses = models.Course.objects.all()
    email = 'questions@learning_site.com'
    # output = ', '.join([str(course) for course in courses])  # Joined Them Together With Commas
    # return HttpResponse(output)
    return render(request, 'courses/course_list.html', {'courses':courses, 'email':email})


def course_detail(request, pk):
    # course = Course.objects.get(pk=pk)
    course = get_object_or_404(models.Course, pk=pk)
    steps = sorted(chain(course.text_set.all(), course.quiz_set.all()), key=lambda step: step.order)
    return render(request, 'courses/course_detail.html', {'course':course, 'steps':steps})


def text_detail(request, course_pk, step_pk):
    step = get_object_or_404(models.Text, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/step_detail.html', {'step':step})


def quiz_detail(request, course_pk, step_pk):
    step = get_object_or_404(models.Quiz, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/quiz_detail.html', {'step':step})

@login_required
def quiz_create(request, course_pk):
    course = get_object_or_404(models.Course, pk=course_pk)
    form = forms.QuizForm()

    if request.method == 'POST':
        form = forms.QuizForm(request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.course = course
            quiz.save()
            messages.add_message(request, messages.SUCCESS, "Викторина қосылды!")
            return HttpResponseRedirect(quiz.get_absolute_url())

    return render(request, 'courses/quiz_form.html', {'form':form, 'course':course})



@login_required
def quiz_edit(request, course_pk, quiz_pk):
    quiz = get_object_or_404(models.Quiz, pk=quiz_pk, course_id=course_pk)
    form = forms.QuizForm(instance=quiz)

    if request.method == 'POST':
        form = forms.QuizForm(instance=quiz, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Updated {}".format(form.cleaned_data['title']))
            return HttpResponseRedirect(quiz.get_absolute_url())

    return render(request, 'courses/quiz_form.html', {'form':form, 'course':quiz.course})

@login_required
def create_question(request, quiz_pk, question_type):
    quiz = get_object_or_404(models.Quiz, pk=quiz_pk)
    if question_type == 'tf':
        form_class = forms.TrueFalseQuestionForm
    else:
        form_class = forms.MultipleChoiceQuestionForm

    form = form_class()
    answer_forms = forms.AnswerInlineFormSet(
        queryset = models.Answer.objects.none()
    )

    if request.method == 'POST':
        form = form_class(request.POST)
        answer_forms = forms.AnswerInlineFormSet(request.POST, queryset = models.Answer.objects.none())

        if form.is_valid() and answer_forms.is_valid():
            question = form.save(commit=False)
            question.quiz = quiz
            question.save()
            answers = answer_forms.save(commit=False)
            for answer in answers:
                answer.question = question
                answer.save()
            messages.success(request, "Қосымша сұрақ")
            return HttpResponseRedirect(quiz.get_absolute_url())

    return render(request, 'courses/question_form.html', {'form':form, 'quiz':quiz, 'formset':answer_forms})


@login_required
def edit_question(request, quiz_pk, question_pk):
    question = get_object_or_404(models.Question, pk=question_pk, quiz_id=quiz_pk)
    if hasattr(question, 'truefalsequestion'):
        form_class = forms.TrueFalseQuestionForm
        question = question.truefalsequestion
    else:
        form_class = forms.MultipleChoiceQuestionForm
        question = question.multiplechoicequestion
    form = form_class(instance=question)
    answer_forms = forms.AnswerInlineFormSet(
        queryset = form.instance.answer_set.all()
    )

    if request.method == 'POST':
        form = form_class(request.POST, instance=question)
        answer_forms = forms.AnswerInlineFormSet(
            request.POST,
            queryset = form.instance.answer_set.all()
        )
        if form.is_valid() and answer_forms.is_valid():
            form.save()
            answers = answer_forms.save(commit=False)
            for answer in answers:
                answer.question = question
                answer.save()

            for answer in answer_forms.deleted_objects:
                answer.delete()    
            messages.success(request, "Жаңартылған сұрақ")
            return HttpResponseRedirect(question.quiz.get_absolute_url())

    return render(request, 'courses/question_form.html', {'form':form, 'quiz':question.quiz, 'formset':answer_forms})


@login_required
def answer_form(request, question_pk):
    question = get_object_or_404(models.Question, pk=question_pk)
    formset = forms.AnswerFormSet(queryset=question.answer_set.all())

    if request.method == 'POST':
        formset = forms.AnswerFormSet(request.POST, queryset=question.answer_set.all())
        if formset.is_valid():
            answers = formset.save(commit=False)

            for answer in answers:
                answer.question = question
                answer.save()
            messages.success(request, "Қосылған жауаптар")
            return HttpResponseRedirect(question.quiz.get_absolute_url())

    return render(request, 'courses/answer_form.html', {'formset':formset, 'question':question})

courses/templates/courses/answer_form.html
{% extends "layout.html" %}
{% load course_extras %}
{% load bootstrap4 %}

{% block title %}{{ question|default:"Жаңа жауап" }} | {{ question.quiz.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
  <li><a href="{% url 'courses:detail' pk=question.quiz.course.pk %}">{{ question.quiz.course.title }}</a></li>
  <li><a href="{% url 'courses:quiz' course_pk=question.quiz.course.pk step_pk=question.quiz.pk %}">{{ question.quiz.title }}</a></li>
  <li>{{ question.prompt }}</li>
{% endblock %}

{% block content %}
  <div class="columns">
    {{ block.super }}
  </div>
  <div class="columns">
    <h1>Answers</h1>
    <form class="" action="" method="post">
      {% csrf_token %}
      <section>
        {% bootstrap_formset formset %}
      </section>
      <input type="submit" class="btn btn-dark" name="" value="Save">
    </form>
  </div>
{% endblock %}

courses/templates/courses/course_detail.html
{% extends "layout.html" %}
{% load humanize course_extras %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
    <article>
        <h2><strong>{{ course.title }}</strong></h2>

        <div class="card-header mt-4">
            {{ course.description|markdown_to_html }}
        </div>

        <h3 class="bg-dark text-white p-3 mt-5">Сонда {{ course.step_set.count|apnumber }} қадам{{ course.step_set.count|pluralize }} осы курста: {{ course.step_set.all|join:", " }}</h3>

        <section>

            {% for step in steps %}
            <div class="card-header">
                <h3><a class="text-success" href="{{ step.get_absolute_url }}">{{ step.title }}</a></h3>
            </div>
                <p class="card-body">{{ step.description }}</p>
                <hr>
            {% endfor %}

        </section>

    </article>

  {% if user.is_authenticated %}
    <hr>
    <a href="{% url 'create_quiz' course_pk=course.id %}" class="btn btn-primary">New Quiz</a>
  {% endif %}

{% endblock %}

courses/templates/courses/course_list.html
{% extends "layout.html" %}
{% load static %}
{% block static %}<link rel="stylesheet" href="{% static 'courses/css/courses.css' %}">{% endblock %}
{% block title %}Қолжетімді курстар{% endblock %}

{% block content %}

    <div class="row mt-4">
        {% for course in courses %}
            <div class="col-md-3">
                <div class="card bg-light mb-3" style="max-width: 18rem;">
                    <div class="card-header">
                        <a href="{% url 'course_detail' pk=course.pk %}">{{ course.title }}</a>
                    </div>
                    <div class="card-body">
                        {% if course.description|wordcount <= 5 %}
                            <p class="card-text">{{ course.description }}</p>
                        {% else %}
                            <p class="card-text">{{ course.description|truncatewords:5 }}</p>
                            <a href="{% url 'course_detail' pk=course.pk %}">Толығырақ оқыңыз</a>
                        {% endif %}
                        <div>Құрылған күні: {{ course.created_at|date:"F j, Y" }}</div>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="mt-4">Сұрақтарыңыз бар ма? Бізбен хабарласыңы! {{ email|urlize }}</div>

{% endblock %}

courses/templates/courses/course_nav.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<div class="container mb-1 row">
{% for course in courses %}
    <div><a class="btn btn-sm" href="{% url 'course_detail' pk=course.pk %}">{{ course.title }}</a></div>
{% endfor %}
</div>

courses/templates/courses/question_form.html
{% extends "layout.html" %}
{% load course_extras %}
{% load bootstrap4 %}

{% block title %}{{ form.instance.prompt|default:"Жаңа сұрақ" }} | {{ quiz.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
  <li><a href="{% url 'detail' pk=quiz.course.pk %}">{{ quiz.course.title }}</a></li>
  <li><a href="{% url 'quiz' course_pk=quiz.course.pk step_pk=quiz.pk %}">{{ quiz.title }}</a></li>
{% endblock %}

{% block content %}
  <div class="columns">
    {{ block.super }}
    <h1>{{ form.instance.prompt|default:"Жаңа сұрақ қойыңыз"}}</h1>
    <form class="" action="" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}

      {{ formset.management_form }}

      <table role="grid" class="table table-striped" style="width: 100%">
        <thead style="background-color: #17b3a3; color: white;">
          <tr>
            <th scope="col" class="text-center" style="width: 10%">Тапсырыс беру</th>
            <th scope="col" class="text-center">Мәтін</th>
            <th scope="col" class="text-center" style="width: 10%">Дұрыс?</th>
            <th scope="col" class="text-center" style="width: 10%">Жою</th>
          </tr>
        </thead>
        <tbody class="order">
          {% for form in formset %}
            <tr class="answer-form {% if form.instance.pk %}item{% else %}new{% endif %}">
              <td>{{ form.id }}{{ form.order }}</td>
              <td class="text-center">{{ form.text }}</td>
              <td class="text-center">{{ form.correct }}</td>
              {% if form.instance.pk %}
                <td class="text-center">{{ form.DELETE }}</td>
              {% else %}
                <td class="text-center"></td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>

      <input type="submit" class="btn btn-dark" name="" value="Save">
    </form>
    <!-- {% if user.is_authenticated and form.instance.pk %}
      <hr>
      <a href="{% url 'create_answer' question_pk=form.instance.pk %}" class="btn btn-secondary">Answers</a>
    {% endif %} -->
  </div>
{% endblock %}


{% block css %}
  {{ form.media.css }}
{% endblock %}


{% block javascript %}
  {% load static %}
  {{ form.media.js }}
  <script src="{% static 'js/vendor/jquery.formset.js' %}"></script>
  <script type="text/javascript">
    $('.answer_form').formset({
      addText: 'жауап қосу',
      deleteText: 'жою'
    });
  </script>
{% endblock %}

courses/templates/courses/quiz_detail.html
{% extends "layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }}{{ block.super }}{% endblock %}

{% block breadcrumbs %}
  <li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
  <div class="columns container">
    <article>
        {{ block.super }}
        <h1 class="mb-4 text-info">{{step.title}}</h1>
        <ul class="no-bullet">
          {% for question in step.question_set.all %}
            <li class="col bg-white">
              <h2 class="mb-4 text-danger">{{ question.prompt }}</h2>
                {% for answer in question.answer_set.all %}
                  <div class="callout border border-muted p-2">
                    {{ answer.text }}
                  </div>
                  <br>
                {% endfor %}
                {% if user.is_authenticated %}
                  <a href="{% url 'edit_question' question_pk=question.pk quiz_pk=step.pk %}" class="btn btn-primary mb-2">Өңдеу</a>
                  <hr>
                {% endif %}
            </li>
          {% endfor %}
        </ul>
    </article>

    {% if user.is_authenticated %}
      <div class="container">
        <hr>
        <a href="{% url 'edit_quiz' course_pk=step.course.pk quiz_pk=step.pk %}" class="btn btn-success">Өңдеу</a>
        <a href="{% url 'create_question' quiz_pk=step.pk question_type='mc' %}" class="btn btn-secondary">Көп таңдаулы жаңа сұрақ</a>
        <a href="{% url 'create_question' quiz_pk=step.pk question_type='tf' %}" class="btn btn-dark">Жаңа ақиқат/жалған сұрақ</a>
      </div>
    {% endif %}

  </div>
{% endblock %}

courses/templates/courses/quiz_form.html
{% extends "layout.html" %}
{% load bootstrap4 %}

{% block title %}{{ form.instance.title|default:"Жаңа викторина"}} | {{ course.title }}{{ block.super }}{% endblock %}

{% block breadcrumbs %}
  <li><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></li>
{% endblock %}

{% block content %}
  <div class="columns">
    {{ block.super }}
    <h1>{{ form.instance.title|default:"Жаңа викторина жасаңыз"}}</h1>
    <form class="" action="" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn=dark" name="" value="Save">
    </form>
  </div>
{% endblock %}

courses/templates/courses/step_detail.html
{% extends "layout.html" %}
{%  load course_extras %}
{% block title %}{{ step.title }} - {{ step.course.title }}{% endblock %}

{% block content %}
    <article>
        <h2><a href="{% url 'course_detail' pk=step.course.pk %}">{{ step.course.title }}</a></h2>
        <h3>{{ step.title }}</h3>

        {% with con=step.content %}
            {{ con|linebreaks }} Мазмұны: {{ con|wordcount }} сөздер. Аяқтауға болжамды уақыт: {{ con|wordcount|time_estimate }} минут {{ con|wordcount|time_estimate|pluralize }}.
        {% endwith %}
    </article>
{% endblock %}

courses/templates/courses/text_detail.html
{% extends "layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }}{{ block.super }}{% endblock %}

{% block breadcrumbs %}
  <li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
  <div class="row columns">
    <article>
        {{ block.super }}
        <h1>{{step.title}}</h1>
        Викторина сұрақтары осында
    </article>
  </div>
{% endblock %}